//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.dataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities8 : DbContext
    {
        public Entities8()
            : base("name=Entities8")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<answersLog> answersLog { get; set; }
        public virtual DbSet<botphrase> botphrase { get; set; }
        public virtual DbSet<entity> entity { get; set; }
        public virtual DbSet<ErrorLog> ErrorLog { get; set; }
        public virtual DbSet<media> media { get; set; }
        public virtual DbSet<OtherLog> OtherLog { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<SubQuestion> SubQuestion { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<intent> intent { get; set; }
        public virtual DbSet<userScore> userScore { get; set; }
        public virtual DbSet<multyEntity> multyEntity { get; set; }
    }
}
