//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.dataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class multyEntity
    {
        public string parts { get; set; }
        public string singleValue { get; set; }
        public string entityType { get; set; }
        public string entityValue { get; set; }
        public int entityID { get; set; }
    }
}
