//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.dataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.SubQuestion = new HashSet<SubQuestion>();
        }
    
        public string QuestionID { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string QuestionText { get; set; }
        public string Flags { get; set; }
        public string questionType { get; set; }
        public string questionMedia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubQuestion> SubQuestion { get; set; }
    }
}
