//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bot_Application1.dataBase
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Question
    {
        public string ID { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string QuestionText { get; set; }
        public string AnswerText { get; set; }
    }
}
